### ISSUE TITLE
멘토님 며칠내내 시도해보았는데 역시나 안되네요 ㅠㅠ

### ISSUE THREAD

**Issue by yoonucho** [henyy1004/nyangterest#105]
@jongfeel 

* 스크롤을 해서 보여지지 않는 데이터들은 왜 필터 기능이 동작하지 않는지에 대한 문제점 찾아보기 

원인은 백엔드에서 데이터를 받아오지 않았기 때문이었습니다.

그래서 받아올수 있는 방법을 이것저것 시도해 보았습니다.

1. 조언해주신대로 listStore.js에 loadList함수안에 아이템에 slice를 하여 아이템을 지워보았습니다.
아이템도 잘지워지고 그아이템은 지워진채로 화면에도 출력되었습니다.

push는 기존 코드에서 걸려서 에러가 나와서 실패하였습니다.

2. Home.js에 render함수안에 필터링 전에 loadMore()를 넣으면
검색한 데이터를 전부 받아오는 것을 확인 하였습니다.

하지만 무작정 쏟아지듯 나오기때문에 속도가 너무 빨라서 누락되는 데이터가 많고 이는 기존 스크롤로 데이터를 보여지는 방식도 영향을 끼쳐서
방법이 아닌거 같습니다.

3. searchStore.js에  categoryChange함수에 loadMore함수를 넣어봤습니다.
하지만 카테고리를 변경후 백엔드데이터가 1페이지정도 받아지고는 더이상 진전이 없습니다.

이거저거 해본 결과 3번에서 검색시 전체데이터를 불러오는 방법이 맞을거 같은데 제생각대로 되지가 않네요 

3번에서 백엔드데이터가 받아지지 않는 이유에 대해서도 계속 생각해보았습니다. 품종에 대한 요청변수가 없어서 그런거 아닐까 싶어서 api에서 제공하는 kind를 요청변수로 넣어서도 시도해보았습니다.

그런데 문제는  예를 들어 품종 중 노르웨이숲을 검색하는 api는 이렇습니다.

http://openapi.animal.go.kr/openapi/service/rest/abandonmentPublicSrvc/abandonmentPublic?ServiceKey=P3gvH0LsdoPkxFnZU2Ee98hGDDEwVTJndJFa8NDUhznSLlZG6OOxBopFWLBmiCPOfWXsF8Wz8LFHJguz41qJvA%3D%3D&_type=json&upkind=422400&kind=000170&bgnde=20191005&endde=20191031&pageNo=1&numOfRows=10& 

노르웨이숲의 코드는 000170입니다.
그런데 전체 품종을 나오게 하려면 kind=&로 하거나 kind에 요청변수를 넣지않아야 제대로 보여집니다. 
http://openapi.animal.go.kr/openapi/service/rest/abandonmentPublicSrvc/abandonmentPublic?ServiceKey=P3gvH0LsdoPkxFnZU2Ee98hGDDEwVTJndJFa8NDUhznSLlZG6OOxBopFWLBmiCPOfWXsF8Wz8LFHJguz41qJvA%3D%3D&_type=json&upkind=422400&kind=&bgnde=20191005&endde=20191031&pageNo=1&numOfRows=10&

kind=&를 리액트로 넘길수 있는 방법도 이거저거 시도해봐도 undifined이 나와서 기존에 잘나오던 데이터도 제대로 나오지 않게 됩니다. ㅠㅠ

이외에도 시도해본 자잘한 방법들이 있는데 제가 이거저거 시도하는게 엉뚱한 짓을 하고 있는건 아닌가 싶어서 이렇게 이슈로 글을 남깁니다. ㅠㅠ

**Comment by jongfeel** [comment]
@yoonucho 

우선 여러 가지 시도를 하고 있고 방법을 모색하고 있는 부분은 잘 진행되고 있는 것입니다.

음 많이 우울하시더라도 이 시기를 잘 견뎌내셨으면 좋겠습니다.
회사에서 이런 일이 일어나면 더 심각한 우울증에 빠질 수도 있거든요.
물론 분위기가 좋은 팀원들이라면 괜찮겠지만
그렇지 못한 팀에서 일하게 될 경우에는 한없이 멘붕에 빠지게 될꺼에요.

윤우님이 적은 글에서 또 뭔가 객관적인 시각에서 이해가 안되거나 빠뜨린 부분이 있는지 찾아보고 그 부분을 관찰해 보면 단서가 나올 수도 있습니다.

동료인 혜인님과 리뷰를 다시 해보시는 건 어떨까요?

저의 의견은
객관적인 데이터가 있지 않고
xxx 해봤는데 안되더라만 있어서요. 그런 부분을 조금 더 정리해 보면 어떨까 싶습니다.

예를 들어
> kind=&를 리액트로 넘길수 있는 방법도 이거저거 시도해봐도 undifined이 나와서 기존에 잘나오던 데이터도 제대로 나오지 않게 됩니다. ㅠㅠ

이 부분에서 어떻게 넘겨서 undefined가 나오는지 왜 그렇게 나오는지에 대한 원인 분석의 결과 정도가 있으면 좋을 것 같아요. 잘 모르는 사람이 보기에는 그냥 삽질하고 있구나 정도로 밖에 느껴지지 않아요.

**Comment by yoonucho** [comment]
@jongfeel  넵 ㅠㅠ 이러고 회사들어라서 일을 제대로 할수 있을까 자괴감도 드네요 
말씀하신대로 제대로 내용을 정리해보겠습니다  혜인님께도 리뷰 요청드렸습니다
