### ISSUE TITLE
멘토님 시간되실때 한번 살펴봐주셔요.

### ISSUE THREAD

**Issue by yoonucho** [henyy1004/nyangterest#112]
@jongfeel 

멘토님 제가 이슈를 해결하려는 노력(?)에 대해 정리한 문서는 아래 링크에 있습니다. https://github.com/henyy1004/nyangterest/blob/master/yu_report/yu_200118_Search.md

결국은 모두 실패는 하였지만 멘토링이 끝나고 나서 이슈에 대해 다시 생각해봤더니
 Promise.all()을 이용하여 동시에 API호출하는 방법이 맞을거 같다 생각하여 조금 더 코드를 수정해보았습니다. 

(방향이 맞는건지 아니면 전혀 엉뚱한 짓을 하고 있는지 한번 봐주세요.)

그 코드문서는 아래 링크에 있고 수정한 코드는 각각 다음과 같습니다.
https://github.com/henyy1004/nyangterest/blob/feature/yu-Code/packages/backend/server.js

```javascript

router.get("/search/:bgnde/:endde/:totalCount/:id/", (req, res) => {
	const { bgnde, endde, totalCount, id } = req.params;

	let baseUrl = `${api}/abandonmentPublic?ServiceKey=${serviceKey}&_type=json&bgnde=${bgnde}&endde=${endde}&upkind=422400&numOfRows=${totalCount}&pageNo=${id}`;

	let apiUrl = `${api}/abandonmentPublic?ServiceKey=${serviceKey}&_type=json&bgnde=${bgnde}&endde=${endde}&upkind=422400&numOfRows=${totalCount}&pageNo=${id}`;

	// combine
	let urls = [baseUrl, apiUrl];

	Promise.all(urls.map(url => fetch(url)
		.then(response => response.json())))
		.then(json => {
			res.send(json.response.body);
			console.log(bgnde, endde, json.response.body.totalCount, url);
		})
		.catch(() => {
			res.send(JSON.stringify({ message: "System Error" }));
		});
});
```
https://github.com/henyy1004/nyangterest/blob/feature/yu-Code/packages/frontend/src/Stores/listStore.js
 
```javascript
@action
	loadList = async (urls) => {
		try {
			const { items, pageNo, happenFrom, happenTo, totalCount } = this;

			let baseUrl = `/search/${happenFrom}/${happenTo}/${totalCount}/${pageNo}`;
			let apiUrl = `/search/${happenFrom}/${happenTo}/${totalCount}/${pageNo}`;

			let urls = [baseUrl, apiUrl];

			console.log(baseUrl, apiUrl)
			const response = await Promise.all(urls.map(url => fetch(url).catch(err => err)))
			const json = await Promise.all(response.map(res => res.json ? res.json().catch(err => err) : res))

			console.log(response, json)

			runInAction(() => {
				if (Array.isArray(json.items.item)) {
					// if (Array.isArray(json.items.item)) {
					this.setItems([...items, ...(json.items.item || [])]);
				}
				else {
					// 객체를 배열로 만들어서 기존배열에 추가하여 새배열을 만드는 코드
					this.items = items.concat(json.items.item).slice();
					console.log(typeof items);
					this.loading = false;
					this.hasMore = false;
				}
				this.setCount(json.totalCount);
			})

		} catch (err) {
			runInAction(() => {
				console.log(err);
				this.isLoading = false;
			})
		}
	};
```
하지만 역시 빈 화면에 로딩중만 돌고 있고
console.log(response, json)를 찍었더니
아래와 같이 response는 제대로 받아졌는데 json은 에러가 나왔습니다.

![주석 2020-01-23 063349](https://user-images.githubusercontent.com/2981954/72936974-9cf18f80-3dab-11ea-8baa-96557ec67ae1.jpg)

VSCODE에서 백엔드쪽 터미널창에서 에러메세지가 뜨지는 않은 상태라 프론트쪽 코드가 문제가 있는거 같아서 아래와 같은 사이트를 참고하여 수정을 해보았지만 에러를 해결하지는 못하였습니다.

 https://stackoverflow.com/questions/50006595/using-promise-all-to-fetch-a-list-of-urls-with-await-statements

https://ko.javascript.info/promise-api

https://stackoverflow.com/questions/50006595/using-promise-all-to-fetch-a-list-of-urls-with-await-statements

멘토님이 해결팁을 주셨을때는 정말 쉬울줄 알았는데  저한테는 이것조차 어려워서 마음이 좀 힘듭니다.. 😹

**Comment by jongfeel** [comment]
@yoonucho 

으흠 Promise.all()은 실행 순서를 보장하지는 못합니다.
그러니까 Promise.all()은 비동기 처리를 순서대로 하는 방법이 아니라는 뜻이죠.

제가 이번에는 코딩을 좀 해서 pull request를 해보도록 할께요
대신 코드 리뷰를 꼼꼼하게 하는 시간을 가져보면 좋을 것 같습니다.

**Comment by yoonucho** [comment]
@jongfeel  아하 역시나 또 삽질을 하고 있던건가요.. 
넵넵 감사합니다 😿
