### ISSUE TITLE
지난주 공부한 내용에 대한 사전안내(?)

### ISSUE THREAD

**Issue by henyy1004** [henyy1004/nyangterest#118]
@jongfeel 

안녕하세요 멘토님!
공부한 내용 미리 알려달라고 하셨는데..ㅎㅎ
매번 공부하는 내용이 달라 당황스러우시져..
너무 늦게 올려서 죄송합니다....!!

[지난 주 공부한 내용에 대한 사전안내?!](https://github.com/henyy1004/nyangterest/blob/master/hi_report/200205_study.md)

멘토링시간에 뵙겠습니다~

**Comment by jongfeel** [comment]
@henyy1004 

지금이라도 알려주셔서 다행입니다!

시간이 늘어지는 걸 방지하기 위해
진짜 계획이라는 걸 얘기해 보는 시간도 가져보면 좋을 듯 합니다.
