### ISSUE TITLE
Let's do Pomodoro timer

### ISSUE THREAD

**Issue by jongfeel** [henyy1004/nyangterest#119]
저번 미팅 시간에 얘기했던
뽀모도로 타이머를 사용해서 시간 관리를 진행 할 거고요.
아래와 같은 시간의 순서로 최대한(?) 맞춰서 진행해보려 합니다.

저의 노력도 필요하겠지만
@yoonucho 님
@henyy1004 님
의 노력도 조금은 필요할 듯 합니다.

잘 진행되었으면 좋겠습니다.

- 11:00 ~ 11:25: 윤우님 리뷰 1
- 11:25 ~ 11:30: 근황토크 종필
- 11:30 ~ 11:55: 윤우님 리뷰 2
- 11:55 ~ 00:00: 근황토크 윤우
- 00:00 ~ 00:25: 혜인님 리뷰 1
- 00:25 ~ 00:30: 근황토크 혜인
- 00:30 ~ 00:55: 혜인님 리뷰 2
- 00:55 ~ 01:00: 아무말 대잔치 && say good night

**Comment by yoonucho** [comment]
@jongfeel 앗 ㅋㅋ 네 노력하겠습니다!

**Comment by henyy1004** [comment]
@jongfeel 잘 진행되도록 노력해보겠스니당!

**Comment by jongfeel** [comment]
## 회고

### 잘못된 점
- 00:00 ~ 00:25: 혜인님 리뷰 1
  - 여기서 부터 시간 체크를 못해서 오버됐는데 다음에는 정확하게 시간 체크를 다시 해보도록 해요
- node 연습하면서 궁금한점 질문
  - 사실 미리 issue에 질문해 볼 수 있는 문제였고, 리뷰 시간에는 시간이 남을 때 질문할 수 있다면 따로 얘기하는게 좋을 것 같아요.
  - 확인: #120

### 잘된 점
- 필요한 얘기만 하기 위한 노력, 실제 해보니까 됨
