### ISSUE TITLE
Next steps: Planning

### ISSUE THREAD

**Issue by jongfeel** [henyy1004/nyangterest#121]
## Planning

- Project에 정한 To do, Doing 기반으로 해야할 일과 범위를 정해주세요.
  - 현재 상태가 마음에 안들면 마음에 들 때 까지 정리하시면 됩니다.
- 그 계획대로 실천한 내용을 여태까지 해 왔던 형태인 문서 정리로 하시는 겁니다.

## Questions

- 질문할 내용을 리뷰 시간에 하는 것 보다 미리 준비해 주세요.
- 즉석에서 질문할 내용이 떠오르면 시간 조절 요청을 해주시고 진행하는 건 어떨까요?

**Comment by yoonucho** [comment]
@jongfeel 네 알겠습니다!

Projects 업데이트를 너무 안하긴 했네요 

질문할 내용은  이슈에 미리 올려둘게요

즉흥적인 질문을 하게된다면 시간연장신청을 요청드리면 될까요? ㅎㅎ

**Comment by henyy1004** [comment]
@jongfeel 
넵넵  계획성있게 진행해보겠습니다~~!!!

**Comment by jongfeel** [comment]
@yoonucho

리뷰 시간에 해도 되지만 원래 리뷰하려는 내용을 못하지 않는 범위내에서 시간 맞춰 해 봐야죠
