### ISSUE TITLE
Code review by github pull request

### ISSUE THREAD

**Issue by jongfeel** [henyy1004/nyangterest#128]
issue에 계속해서 code + screenshot + description을 써 주고 계신데
이걸 github pull request + code review로 하면 깔끔하게 됩니다.

이렇게 해 보는 건 어떨까요?

실제 facebook/react 에서 하고 있는 pull request code review는 이렇습니다.
https://github.com/facebook/react/pull/18187

**Comment by yoonucho** [comment]
@jongfeel 아하! 네 다음엔 PR로 시도해보겠습니다.

**Comment by jongfeel** [comment]
#129 

처음이지만 성공적으로 pull request를 한 것 같습니다.

다만 양이 너무 많아서 조금씩 자주 pull request를 주면 좋을 것 같네요.
