### ISSUE TITLE
IE도 적용 할건가요?

### ISSUE THREAD

**Issue by jongfeel** [henyy1004/nyangterest#13]
IE polyfill이 있길래요

**Comment by yoonucho** [comment]
헙 이제 봤네요 넵 IE에서도 적용하는게 낫지 않을까 싶어서요

**Comment by jongfeel** [comment]
사실 IE는 진짜 안써도 되는 추세라 없어도 상관 없을 거 같긴 한데
하신다니까 말리진 않겠습니다!

**Comment by yoonucho** [comment]
아하 그럼 필요성에 대해 좀더 생각해보고 결정하겠습니다!
