### ISSUE TITLE
필터링의 조건을 말로 풀어서 정리하기, 즉 설계 문서 만들기를 어딘가에 적어 뒀으면 좋겠습니다.

### ISSUE THREAD

**Issue by jongfeel** [henyy1004/nyangterest#130]
필터링의 조건을 말로 풀어서 정리하기, 즉 설계 문서 만들기를 어딘가에 적어 뒀으면 좋겠습니다.

_Originally posted by @jongfeel in https://github.com/henyy1004/nyangterest/pull/129_

**Comment by yoonucho** [comment]
@jongfeel 헙 메일이 안와서 이제 확인했네요 네 따로 문서를 작성하겠습니다.

**Comment by jongfeel** [comment]
되도록이면 지금 하려고 하는 기능의 충분한 설계
- 필터링을 하기 위한 데이터 구조
- 데이터가 어떻게 오고 가는지
- 요청 API는 정확히 어떻게 되는지
- 스크롤 기능을 위해 다시 생각해 봐야 하는 요소는 무엇인지

가능하면 그림이 필요하다면 그림을 추가
- 화면 설계 이미 있으니까 (X)
- front-end <-> server <-> public API

**Comment by yoonucho** [comment]
@jongfeel  멘토님 안녕하세요

일주일도 넘었는데 그간 내용이 업데이트가 되지 않았었네요. 😢 

우선 설계문서에 대한 샘플이나 정보를  찾고 싶어서 구글링을 하여서 글들을 찾아서 읽어보았습니다
https://wanna-b.tistory.com/83
https://brunch.co.kr/@devcrema/2
http://www.allofsoftware.net/2011/12/blog-post_22.html

그런데 제가 적용하기에는 무리가 있다 생각하였습니다.

이후 설계문서를 작성해보고는 있었는데 똑같은걸 계속 반복해서 다시 쓰는 느낌도 들고 이게 설계가 아닌거 같다는 생각이 들었습니다.
![photo_2020-03-13_17-28-54](https://user-images.githubusercontent.com/2981954/76604292-d21b9200-6551-11ea-900a-338ada2570ee.jpg)

https://github.com/henyy1004/nyangterest/blob/feature/yu-Search/packages/backend/fiterDesign.md

그래서 API툴인 [swagg](https://swagger.io/)를 보게 되어서 이거에 대한 [튜토리얼](https://app.swaggerhub.com/apis/yoonucho/API_Example/1.0.0)도 따라해봤는데 다하고 나서 든 생각은 멘토님이 말씀하신건 이런건 아니겠구나라고 깨닫게 되었습니다.

그리고 저는 설계와 구현을 동시에 하려고 생각하고 있다보니 계속 코드를 수정하고 싶은 맘이 들었고 이러면 기존하고 다를바가 없겠다는 생각이 들어서 코드를 조금 수정하던것도 중단을 하였습니다.

이거에만 매달려있으니 유닛테스트나 다른 해야 할 일들이 점점 미뤄지는거 같은데 우선 중단하고 다른걸 해야할까라는 생각도 듭니다.

**Comment by jongfeel** [comment]
일단 마음 고생이 좀 있으셨겠네요.
코딩이 아닌 일을 해야하기 때문에 더 어렵다고 느껴지셨을 수도 있습니다.

우선 자세한 내용은 나중에 보고 피드백 드리면 될 거 같고.
지금 짧게 얘기해 드리면
"누군가의 문서를 보고 이해하는 것과 누군가를 이해시키기 위한 문서를 작성하는 작업"에는 차이가 있다는 걸 많이 느끼셨으면 그걸로 충분합니다.
잘하고 못하고는 중요하지 않은 거 아시죠?

그럼 시간내서 코멘트 또 달겠습니다.

**Comment by yoonucho** [comment]
@jongfeel 멘토님께 피드백을 받으면 정말 큰 위안이 됩니다. 😃 
 이후 설계 문서를 조금 더 수정하였습니다.
https://github.com/henyy1004/nyangterest/blob/feature/yu-Search/packages/backend/fiterDesign.md

**Comment by jongfeel** [comment]
일단 쓸 내용이 많아서요.

각각 하나씩 issue로 만들어서 링크를 달께요. 필요한 내용은 계속 코멘트 달아 주시고 issue close는 윤우님이 판단해서 해주시면 됩니다.

**Comment by yoonucho** [comment]
@yoonucho  네 알겠습니다!

**Comment by jongfeel** [comment]
2주간 적은 내용을 보고 얘기해보면 좋겠습니다
