### ISSUE TITLE
Unit test 진행

### ISSUE THREAD

**Issue by jongfeel** [henyy1004/nyangterest#132]
일단 만들어 보시고 reviewer로 설정해 주세요.

필요성에 대해서 의구심이 든다면
왜 필요한지를 생각해 보면 좋은데
지금 server api 만드는 과정에서 느껴 보시면 좋을 것 같습니다.

당장 적용하기 어려우면
tutorial 코드라도 적용해 보고 review 요청 해주세요.

**Comment by yoonucho** [comment]
우선 아카이브에 넣었다가 나중에 복구할때 이슈도 다시 열자.

**Comment by yoonucho** [comment]
1. 우선 유닛테스트 튜토리얼 영상 시청을 하자.

**Comment by jongfeel** [comment]
어떤 영상을 시청하고 있고
어떤 결과(결론?성과?)를 얻을 수 있는지 적으면 좋겠습니다.

**Comment by yoonucho** [comment]
@jongfeel 아직 맘에 드는 영상을 찾지 못해서 골라(?)보고 있습니다.
