### ISSUE TITLE
Debugger 적응하기

### ISSUE THREAD

**Issue by jongfeel** [henyy1004/nyangterest#133]
해보면서 역시 필요성을 느껴야 함

되도록이면 console.log를 안찍고 확인하는 방향으로 진행
console.log는 디버깅 확인용이 아닌, 데이터 확인 용으로 써보도록 노력해보기

디버깅 하는 방법 live coding

**Comment by yoonucho** [comment]
우선 아카이브에 넣었다가 나중에 복구할때 이슈도 다시 열자.
