### ISSUE TITLE
시작 날짜와 끝 날짜의 범위 추가

### ISSUE THREAD

**Issue by jongfeel** [henyy1004/nyangterest#137]
#130 [날짜 검색](https://github.com/henyy1004/nyangterest/blob/feature/yu-Search/packages/backend/fiterDesign.md#%EB%82%A0%EC%A7%9C-%EA%B2%80%EC%83%89)과 연결됨

### Questions

- 유기동물 정보 조회 서비스 OpenAPI (이하 OpenAPI)의 유효한 날짜의 범위가 있나요? 최소, 최대 기간이 있을까요?
  - 예1) 현재 날짜 기준으로 최근 한달만 된다.
  - 예2) 혹은 현재 날짜와 상관 없이 검색 기간은 최대 3달 기간만 된다.
- 또 그에 따라 조회되는 결과의 유효 범위가 달라지나요?
  - 예1) 최대 기간으로 조회해도 결과 조회 건수는 1000건을 초과하지 않는다.
  - 예2) 오늘 날짜 기준으로 한달 기간을 조회해도 500건, 15일 기간을 조회해도 500건이라면 내부적으로 최대 날짜 유효범위가 현재 날짜 기준 15일이라는 걸 찾을 수 있나요?

### 제안

Front에서 검색을 위해 시작 날짜와 끝 날짜의 유효 범위와 기본 기간을 OpenAPI의 유효 범위에 맞게 추가하면 어떨까요?

**Comment by yoonucho** [comment]
@yoonucho  멘토님 안녕하세요 
OpenAPI에는 날짜에 대한 제한은 없는거 같습니다.
제가 현재 날짜기준으로 4년전 날짜로 조회하여도 데이터가 나오는걸  확인하였습니다.

![주석 2020-03-16 173724](https://user-images.githubusercontent.com/2981954/76737912-fde68400-67ac-11ea-92ae-3b0040a4b5f9.jpg)
![주석 2020-03-16 173816](https://user-images.githubusercontent.com/2981954/76737915-ff17b100-67ac-11ea-8f23-d2cbd3d1a36a.jpg)

**Comment by jongfeel** [comment]
그러면, 적절한 날짜 유효범위를 추가해 보는 건 어떨까요? 화면이 느려지지 않는 적당한 유기 동물 데이터의 갯수를 선택해서 정하는 거죠.

UI의 편의를 위해 기본 날짜 범위를 지정할 수 있도록 해주면 좋을 것 같습니다.

이후 설계 문서를 업데이트 할 때 front-end 쪽에 조건을 추가하는 거죠.
예를 들어 - 검색 조건의 기간은 얼마든지 변경 가능하지만 검색의 편의성 (데이터양)을 위해 3달 기간의 유기 동물 검색만 허용함.

**Comment by yoonucho** [comment]
@jongfeel  네 그러면 테스트해보고 적정선을 찾아보겠습니다.
그리고 멘토님께 코멘트단 이후  든 생각이 한 api당 요청은 1000건이 한도인게 생각이 났습니다.
그것도 고려해서 생각해보겠습니다.

**Comment by jongfeel** [comment]
어 그것도 질문에 포함되어 있긴 했는데
서버에서 OpenAPI에 호출 횟수를 줄일 수 있도록 할 수 있는 방법을 생각해 보는 것입니다.

이 질문도 따로 올릴게요

**Comment by yoonucho** [comment]
https://github.com/henyy1004/nyangterest/commit/1dd92f52bd616fd289fdb3bcaee66435b7282acd#r37881118
