### ISSUE TITLE
품종에 대한 enum 값 제안

### ISSUE THREAD

**Issue by jongfeel** [henyy1004/nyangterest#138]
#130 [검색 조건](https://github.com/henyy1004/nyangterest/blob/feature/yu-Search/packages/backend/fiterDesign.md#url) 관련 이슈

`kind==="000116"`

이런 개발 코드가 들어가 있는데, 설계 문서에는 사실 코드가 추가될 수도 있지만 이런 경우에는 코드 보다는 `000016`이 의미하는게 무엇인지 적는게 더 보기 좋은 문서가 될 것입니다.

또 `000116`에 해당하는 뜻이 무엇인지, 또 품종 코드 별로 뜻하는 바가 무엇인지 enum 값으로 정리해 두고 그걸 코드에 사용한다면 더 보기 좋은 코드가 될 것 같습니다.

**Comment by yoonucho** [comment]
@jongfeel  말씀대로 그 코드는 사실 저만 아는 코드였네요!  각 품종에 대한 코드도 정리해두겠습니다.

**Comment by jongfeel** [comment]
enum이 javascript에는 없는 문법이네요. 다른 언어에서는 자연스럽게 쓰는 문법이라서 저도 생각 없이 써 놓은 것 같습니다.
꼭 symbol로 하지 않더라도 key, value로 볼 수 있는 어떤 상수 타입의 객체만 있으면 됩니다.

**Comment by yoonucho** [comment]
@jongfeel  

네 심볼형에 대한 내용은 여러개 찾아서 읽어보고 적용해보려고 시도했었는데 개념을 제대로 이해하지 못한 상태로 적용하려니 원하는대로 되지 않았습니다.

이후 품종에 대한 코드번호를 표 형식으로 만들어 두었는데 객체로 만들어두는게 설계문서에는 더 적합한건가요?
