### ISSUE TITLE
POST 방식이어야 하는 이유에 대한 질문

### ISSUE THREAD

**Issue by jongfeel** [henyy1004/nyangterest#139]
#130 [POST 방식에 대한 이유](https://github.com/henyy1004/nyangterest/blob/feature/yu-Search/packages/backend/fiterDesign.md#api) 관련 이슈

---
유기동물 정보 조회 서비스 open api에서 제공하는 요청변수에는 검색어에 대한 정보가 없음으로 프론트에서 검색어로 입력한 값을 body로 요청해서 받아온다.
따라서 검색어로 입력한 값은 post방식으로 요청해야 한다.
---

이렇게 적어 놓으셨는데 질문이 있습니다.
유기동물 정보 조회 서비스 open api (이하 OpenAPI)에서 제공하는 요청변수와 상관없이 front-end에서 요청했을 때 검색어 요청 변수도 GET으로 받아와도 되지 않나요?
단순히 OpenAPI에는 제공되지 않는 값이니까 GET 방식으로 받아올 수 있는 데이터인데도 POST로 받을 이유가 없는 것 같아요.
그리고 정작 POST로 받던 GET으로 받던 OpenAPI에 요청하는 방식은 똑같은데, 구분할 이유가 없어 보입니다.

**Comment by yoonucho** [comment]
@jongfeel  움.. 제 생각이 잘못된거 같습니다 ㅠㅠ

제가 생각했던건  get으로 요청을 하려면 요청변수로 받아서 url에 넣어야  하는데
open api가 제공하지 않는 요청변수를 넣으면 에러가 난다고 생각했거든요
(처음에 시도할때는 localhost:3000/input/searchFiled 이런식으로 get방식 api를 만들어보긴했었지만 계획대로 되지 않아서 그렇게 생각하게 되었었습니다.)

아니면  http://localhost:3000/page/20200309/20200316/000200/72/1/searchField 이게 가능하다는 말씀이신거지요?

그리고저번에 코드리뷰 코멘트 달아주셨을때 https://github.com/henyy1004/nyangterest/pull/129#discussion_r386834958 이부분이 있는데
저는 이게 역시 body로만 받을수 있다는건 줄 알았습니다. 😢

**Comment by jongfeel** [comment]
> @jongfeel 움.. 제 생각이 잘못된거 같습니다 ㅠㅠ
> 
> 제가 생각했던건 get으로 요청을 하려면 요청변수로 받아서 url에 넣어야 하는데
> open api가 제공하지 않는 요청변수를 넣으면 에러가 난다고 생각했거든요
> (처음에 시도할때는 localhost:3000/input/searchFiled 이런식으로 get방식 api를 만들어보긴했었지만 계획대로 되지 않아서 그렇게 생각하게 되었었습니다.)
> 
> 아니면 http://localhost:3000/page/20200309/20200316/000200/72/1/searchField 이게 가능하다는 말씀이신거지요?
> 
> 그리고저번에 코드리뷰 코멘트 달아주셨을때 [#129 (comment)](https://github.com/henyy1004/nyangterest/pull/129#discussion_r386834958) 이부분이 있는데
> 저는 이게 역시 body로만 받을수 있다는건 줄 알았습니다. 😢

GET method에서 가능한 방법 중에 하나는 parameter 전달입니다.
그러니까 지금 방법은 routing에 의한 parameter 전달이고
원래 GET method parameter로 해보면 아래와 같게 할 수 있습니다.

http://localhost:3000/page/20200309/20200316/000200/72/1?searchField=멈뭄미

또 POST method의 body로만 받을 수 있다는 얘기는 아니었고,
이미 POST method로 바꾸고 구현 했기 때문에 그 이후에 얘기를 해 드린 겁니다.

**Comment by yoonucho** [comment]
@jongfeel  멘토님 그러면 궁금한 부분이 있는데요 그럼 req.param과 req.query를 같이 사용할수 있는건지요
 http://localhost:3000/page/20200309/20200316/000200/72/1?searchField=멈뭄미 
여기에서 ?searchField=멈뭄미전까지 코드는 req.param 이건 멘토님이 말씀하신대로  routing에 의한 parameter 전달이고 searchField=멈뭄미는 req.query는 쿼리스트링 parameter 전달이 되는거 같은데 이 두개를 같이 사용할 수 있는지 궁금합니다.

**Comment by jongfeel** [comment]
변수가 다른데 당연히 되죠. (req.param, req.query)

**Comment by yoonucho** [comment]
@jongfeel 헉! 그렇군요! 둘이 비교하는 글은 있는데 같이 쓰는 예시는 본적이 없어서 안될거라고 생각했었습니다!

**Comment by jongfeel** [comment]
실제로 되는지 안되는지 해보셨으면 금방 파악이 됐었을겁니다.

**Comment by yoonucho** [comment]
@jongfeel 네 같이 사용할수 없을거라고 생각한 선입견이 적용해볼 기회를 놓치게 된거 같습니다.
