### ISSUE TITLE
API에 대한 설명 추가

### ISSUE THREAD

**Issue by jongfeel** [henyy1004/nyangterest#140]
#130 이슈에서 [API](https://github.com/henyy1004/nyangterest/blob/feature/yu-Search/packages/backend/fiterDesign.md#get) 관련

각 API를 호출하면 뭘 얻을 수 있는지 설명이 필요합니다.
- defaultRes: url을 호출하여 응답받은 기본 데이터를 담은 json객체이다.
- kindAddRes: kindAddUrl을 호출하여 응답받은 데이터(선택한 품종의)를 담은 json객체이다.

이것만 가지고는 뭘 하려는 건지 알 수가 없습니다. json 안의 내용이 어떻게 들어있는지 추가가 필요할 거 같아요.

카카오 개발자 문서를 보고 어떻게 설명하면 좋을지 힌트를 얻어봤으면 좋겠습니다.
https://developers.kakao.com/docs/restapi/search#%EC%9D%B4%EB%AF%B8%EC%A7%80-%EA%B2%80%EC%83%89

**Comment by yoonucho** [comment]
@jongfeel  아항 네 알려주신 링크를 보고 참고하겠습니다. 감사합니다.
