### ISSUE TITLE
API Request 4개를 합칠 수 있는 방법

### ISSUE THREAD

**Issue by jongfeel** [henyy1004/nyangterest#141]
#130 [API](https://github.com/henyy1004/nyangterest/blob/feature/yu-Search/packages/backend/fiterDesign.md#get) 내용에서

4개의 API가 호출하는 parameter를 빼고는 크게 다를게 없어 보입니다.
하나로 합칠 수 있지 않을까요?

**Comment by yoonucho** [comment]
@jongfeel  고민해보겠습니다.

**Comment by jongfeel** [comment]
합치긴 했지만 하나로 될 거 같습니다.

프론트에서 서버로 요청하는 변수가
- 날짜 검색: bende, endde
- 품종 검색: kind
- 검색어 검색: searchField

이렇게 총 4개입니다.

나머지 두개는 스크롤 기능, 즉 UI와 상관 없는 변수입니다.
- 한 페이지에 보여줄 갯수: numOfRows
- 페이지 번호: id

날짜는 기본 1주일 기간이 저장되어 있으니까 항상 입력된다고 보고요
품종도 선택 안하면 전체, 선택하면 해당 품종 검색이겠죠?
검색어도 마찬가지로 입력 안하면 전체, 입력하면 입력된 값이 포함된 검색이고요

그러면 API 설계를 다음과 같이 단순하게 하나로 할 수 있다고 봅니다.

/url/:bgnde/:endde/:kind?searchField=검색어

혹시 이렇게 하나로 했을 때 문제가 있는 게 있을까요?

**Comment by yoonucho** [comment]
@jongfeel  

* open api에서 기본 url에 kind의 값에 "000116"이 들어가면 데이터가 나오지 않습니다. 다른 품종코드를 넣었을때는 제대로 나오고요 

> Request (url에 요청변수 kind=000116을 넣었을 때)
http://openapi.animal.go.kr/openapi/service/rest/abandonmentPublicSrvc/abandonmentPublic?ServiceKey="서비스키"&upkind=422400&kind=000116&bgnde=20191005&endde=20191031&pageNo=1&numOfRows=80

> Response
{"response":{
"header":{"resultCode":"00","resultMsg":"NORMAL SERVICE."},
"body": 
  {"items":"","numOfRows":80,"pageNo":1,"totalCount":0}}}

> Request (요청변수 kind를 넣지 않거나 kind의 값이 없을때)
http://openapi.animal.go.kr/openapi/service/rest/abandonmentPublicSrvc/abandonmentPublic?ServiceKey="서비스키"&upkind=422400&bgnde=20191005&endde=20191031&pageNo=1&numOfRows=80

> Response
{
  "response": {
    "header": {
      "resultCode": "00",
      "resultMsg": "NORMAL SERVICE."
    },
    "body": {
      "items": {
        "item": [
          {
            "age": "2019(년생)",
            "careAddr": "경기도 양주시 남면 상수리 410-1",
            "careNm": "한국동물구조관리협회",
            "careTel": "031-867-9119",
            "chargeNm": "지역보건과",
            "colorCd": "흰색 바탕 노랑 포인트",
            "desertionNo": 411316201900697,
            "filename": "http://www.animal.go.kr/files/shelter/2019/11/201911070811103_s.jpg",
            "happenDt": 20191031,
            "happenPlace": "천왕동",
            **"kindCd": "[고양이] 한국 고양이",**
            "neuterYn": "N",
            "noticeEdt": 20191118,
            "noticeNo": "서울-구로-2019-00242",
            "noticeSdt": 20191107,
            "officetel": "02-860-2428",
            "orgNm": "서울특별시 구로구",
            "popfile": "http://www.animal.go.kr/files/shelter/2019/11/201911070811103.jpg",
            "processState": "종료(기증)",
            "sexCd": "F",
            "specialMark": "이유기 자묘",
            "weight": "0.32(Kg)"
          },
         {
            "age": "2016(년생)",
            "careAddr": "대전광역시 유성구 갑동로15번길 20-39 (갑동) ",
            "careNm": "대전동물보호센터",
            "careTel": "042-825-1118",
            "chargeNm": "조원배",
            "colorCd": "백검 ",
            "desertionNo": 430365201901026,
            "filename": "http://www.animal.go.kr/files/shelter/2019/10/201911041011343_s.jpg",
            "happenDt": 20191031,
            "happenPlace": "정생동 773-6 번지 주변 ",
            **"kindCd": "[고양이] 페르시안-페르시안 친칠라",**
            "neuterYn": "U",
            "noticeEdt": 20191114,
            "noticeNo": "대전-중구-2019-00771",
            "noticeSdt": 20191104,
            "officetel": "042-606-7263",
            "orgNm": "대전광역시 중구",
            "popfile": "http://www.animal.go.kr/files/shelter/2019/10/201911041011343.jpg",
            "processState": "종료(입양)",
            "sexCd": "Q",
            "specialMark": ",",
            "weight": "4.00(Kg)"
          },
,..중략

> Request (러시안블루로 조회했을때)
http://openapi.animal.go.kr/openapi/service/rest/abandonmentPublicSrvc/abandonmentPublic?ServiceKey="서비스키"&upkind=422400&kind=000172bgnde=20191005&endde=20191031&pageNo=1&numOfRows=80

> Response

  "response": {
    "header": {
      "resultCode": "00",
      "resultMsg": "NORMAL SERVICE."
    },
    "body": {
      "items": {
        "item": [
          {
            "age": "2015(년생)",
            "careAddr": "경기도 양주시 남면 상수리 410-1",
            "careNm": "한국동물구조관리협회",
            "careTel": "031-867-9119",
            "chargeNm": "서대웅",
            "colorCd": "회",
            "desertionNo": 411308201900611,
            "filename": "http://www.animal.go.kr/files/shelter/2019/10/20191101171111_s.jpg",
            "happenDt": 20191031,
            "happenPlace": "도봉로 95길 64-6 인근",
            **"kindCd": "[고양이] 러시안 블루",**
            "neuterYn": "Y",
            "noticeEdt": 20191111,
            "noticeNo": "서울-강북-2019-00310",
            "noticeSdt": 20191101,
            "officetel": "02-901-6452",
            "orgNm": "서울특별시 강북구",
            "popfile": "http://www.animal.go.kr/files/shelter/2019/10/20191101171111.jpg",
            "processState": "종료(안락사)",
            "sexCd": "M",
            "specialMark": "순댕이라고적힌스카프착용. 코회색. 과체중. 얌전함/사람따름. 털상태양호. ",
            "weight": "8.0(Kg)"
          },
*  그런데 제가 kind에 000116을 넣은 이유는 프론트에서 selectedCategory에 입력된 값을 백엔드에서는 kind의 값으로 받아오는데 빈스트링("")을 넣었더니 제대로 응답을 받아오지 못해서 코드번호를 넣었습니다.
(실제 전체고양이코드가 000116은 맞기도 하니까요 )

* 요청 품종코드는 open api에서 제공하는 품종 조회 OPEN
 API를 요청하여 응답받은 코드를 보고 참고하였었습니다.

> Request
 open api url: http://openapi.animal.go.kr/openapi/service/rest/abandonmentPublicSrvc/kind?serviceKey="서비스키"&up_kind_cd=422400

> Response
![kindlist](https://user-images.githubusercontent.com/2981954/76893157-ca2a5d80-6883-11ea-94dc-e55bc891aa1b.jpg)

**Comment by yoonucho** [comment]
@jongfeel 라우팅 url은 말씀하신 /url/:bgnde/:endde/:kind/:numOfRows?searchField=검색어 이걸로 가능할거 같습니다. post요청을 안해도 되니깐요

**Comment by jongfeel** [comment]
OpenAPI에 request parameter 중에 kind string을 붙이고 안붙이고의 차이를 if문으로 만들고
OpenAPI string을 한번에 만들 수 있으면 됩니다.

``` javascript
let openAPIurl = "http://openapi....../";

const kindparam = "";
if (kind != "")
  openAPIurl  += "&kind=" + kindparam;
```
