### ISSUE TITLE
무한스크롤 기능 가설 검증

### ISSUE THREAD

**Issue by jongfeel** [henyy1004/nyangterest#142]
# 긴급 업데이트! 어쩌면 더 좋은 방법이 있을 수도 있네요. 아래 내용은 무시하고 참고만 해 주세요.

> **영어로 된 변수 이름, json, javascript code가 들어가면 너무 어려울 수 있으니까 되도록이면 쉽게 설명하도록 할께요**
> 
> ### 개요
> 
> #### 무한스크롤 정의
> 
> 유기동물의 리스트를 보여주는 화면에서 스크롤을 내릴 때 마다 일정 갯수의 리스트를 추가로 보여주는 방식
> 실제 예) 페이스북의  포스팅들은 갯수가 정해지지 않고 스크롤을 내릴때 마다 다음 포스팅을 무한으로 보여준다.
> 
> #### 냥터레스트에서의 구현 방법
> 
> 한 화면에 보여줄 수 있는 유기동물 아이템의 갯수가 1000건 이상으로 엄청 많으면 넘어가면 스크롤 하기가 힘드므로 적당한 갯수를 보여주고 계속해서 스크롤 할 때 마다 동적으로 로딩하여 보여주는 방식으로 진행
> 
> ### 동작 방식
> 
> 유기 동물의 전체 갯수를 확인할 방법이 없으므로 동적 페이지 로딩을 언제까지 해야 하는지 모른다.
> 
> 따라서
> 
> 1. 유기 동물 전체 갯수를 파악하기 위해 유기 동물 OpenAPI를 통해 전체 갯수를 확인한다.
> 2. 전체 갯수를 파악한 후 보여주고 싶은 만큼의 데이터의 `갯수`와 `페이지 번호`를 OpenAPI를 통해 얻어온다.
> 
> 이렇게 한게 현재까지의 내용
> 
> 다시 정리하면
> 총 1000건의 유기동물 아이템이라고 했을 때
> 50건 씩 보여준다면
> 총 20 페이지가 생성되므로
> 20번의 동적 로딩이 발생함.
> 
> ### 가설
> 
> 만약 전체 갯수를 모른다고 해도 `갯수`와 `페이지 번호`를 적절히 호출해 준다면 잘 동작하지 않을까?
> 
> 전체 유기동물 갯수가 1000개 라고 가정
> numOfRows=페이지당 보여줄 개수
> pageNo=페이지 번호
> 
> ### 테스트
> 
> #### 첫번째 로딩
> 
> 100개를 읽어옴
> 요청:
> numOfRows=100&pageNo=1
> 결과:
> items=100
> totalCount=1000
> 
> #### 두번째 로딩
> 
> 200개를 읽어옴
> 요청:
> numOfRows=200&pageNo=2
> 결과:
> items=200
> totalCount=1000
> 
> #### 세번째 로딩
> 
> 500개를 읽어옴
> 요청:
> numOfRows=500&pageNo=3
> 결과:
> items=500
> totalCount=1000
> 
> #### 네번째 로딩
> 
> 300개를 읽어옴
> 요청:
> numOfRows=300&pageNo=4
> 예상결과:
> items=200
> totalCount=1000
> 실제결과:
> items=???
> totalCount=1000
> 
> 이미 총 갯수가 1000개라는 걸 알고 있으므로 4번째 페이지 로딩에서 300개를 읽어온다고 해도 나머지는 200개 뿐이므로 200개가 로딩되어야 함
> 
> 해 보시고 결과를 알려주세요.
> 
> 만약 이게 된다면 **전체 갯수를 알기 위한 호출은 필요가 없어집니다.**
> - 물론 검색어를 입력해서 검색했을때 말고요, 날짜+품종 검색했을때만 가능한 방법입니다.
> - 검색어를 입력해서 검색할 때는 전체 아이템을 가져오기는 해야 겠죠, 그 안에서 검색어 매칭일 해야 하니까요.~~

**Comment by yoonucho** [comment]
@jongfeel  헙 이거를 이제 봤네요 지금 테스트해볼게요

**Comment by yoonucho** [comment]
@jongfeel  
open api에서 numOfRows와 pageNo를 변경해보면서 테스트해봤는데요
저는 2020년 2월 14일부터 2020년 3월 18일까지의 데이터를 조회해보았습니다.
totalCount가 1023이 나왔습니다.

멘토님이 말씀하신대로 numOfRows=100&pageNo=1,  numOfRows=200&pageNo=2,  numOfRows=500&pageNo=3,  numOfRows=300&pageNo=4를 요청했습니다.

예상대로라면 numOfRows=300&pageNo=4때는 아이템이 223개가 나와야 하는데 123개가 나오더라고요.

제가 이상하다싶어서 numOfRows=400&pageNo=4를 넣어봤더니 아이템이 0개이더라고요

open api에서는 numOfRows의 갯수를 pageNo의 평균갯수로 생각하는거 같더라고요 

그러니깐 제가 numOfRows=300&pageNo=4를 넣은게  pageNo1~3까지의 numOfRows는 각각 300개가 되었던거고  마지막 남은 페이지에서는  123개의 아이템이 남습니다.

**Comment by jongfeel** [comment]
예상대로는 아니지만 내부 로직이 있는 건 맞았네요.
페이지 카운트랑 상관 없이 한 페이지에 보여질 아이템 갯수를 큰 숫자를 요청하고 받은 전체 유기동물 아이템 갯수를
front에서 요청한 한 페이지에 보여질 아이템 갯수 만큼을 나누면 페이지 카운트가 나오겠네요.

**Comment by jongfeel** [comment]
어제 밤에 너무 대충 써서 다시 제대로 썼습니다.

**Comment by jongfeel** [comment]
확인 하시고 close 하시면 되요. @yoonucho

**Comment by yoonucho** [comment]
@jongfeel  네 확인하였습니다! 감사합니다!
