### ISSUE TITLE
2020-03-18, 23번째 미팅 이야기 할 내용 정리

### ISSUE THREAD

**Issue by jongfeel** [henyy1004/nyangterest#144]
### Design documents

- 설계 문서를 쓰는 방법에 대한 훈련을 많이 해야 합니다.
- 본인이 읽어보고 스스로 피드백을 주는 훈련도 해야 합니다.
- 남이 써 놓은 문서를 보고 피드백을 줄 수 있다면 그것도 좋은 훈련이 됩니다.

**코딩은 사실 왠만하면 못하는 사람은 없다고 보는데, 설계 문서 작성은 아무나 할 수 없습니다**

### Progress feedback

- 제가 피드백 드린 내용에 대해서는 빠르게 이해하고 잘 수정하고 계십니다.
- 하지만, 이건 결국 큰 그림에서 시키는 대로 하는 것에서 크게 벗어나지 못하고 있다는 건 아셔야 합니다.
- 이것 마저도 안되고 있었기 때문에 도움을 드린 거라 생각해 주세요.
- 이 이야기의 근거는 2주간 먼저 쓰신 issue가 하나도 없습니다. issue 글의 작성자는 모두 저입니다.

### Feedback comment

commit한 문서에 comment를 달아 주셨는데요
- https://github.com/henyy1004/nyangterest/commit/1dd92f52bd616fd289fdb3bcaee66435b7282acd
이렇게 하면 나중에 찾기가 힘듭니다. pull request 방식으로 해주세요.
- 한가지 더, 수정중인 문서라고 업데이트 하지 마시고 중간 완료본이라도 수정중이라는 말은 없는게 나은거 같습니다. 어떤 느낌이냐 하면 수정중이니까 완료되면 봐야지 라는 생각입니다.

### Flow drawing

데이터의 흐름에 대한 그림을 추가했으면 좋겠습니다. 그 흐름에 맞춰서 front-end 에서는 어떤 기능을 구현할 수 있는지 back-end 에서는 어떻게 데이터를 모으고 전달해 주는지 간단한 내용이 있으면 됩니다.

**Comment by yoonucho** [comment]
@jongfeel 

**Design documents**
네 설계문서를 작성하는게 너무 어려웠습니다. 😢 

**Progress feedback**
이거는 사실 찔리는 부분이 많습니다

조금의 변명을 하자면 제가 올린 이슈가 없는 이유는 멘토님이 올린 이슈에 관한 내용이라 댓글 형식으로 다는게 맞겠다 생각했습니다.  

그래도 Projects에라도 좀더 세분화해서 올릴수 있었는데 제가 설계문서라는 하나의 미션으로 생각했던거 같습니다.

**Feedback comment**
네  앞으로는 PR로 드리겠습니다.  커밋시 수정중이라는 단어가 그런 생각이 들게 하는줄은 몰랐네요. 

**Flow drawing**
네 변경된 내용에 맞게 업데이트해보겠습니다.

**Comment by jongfeel** [comment]
설계 문서에 변수 이름이 들어가는건 지양해야 합니다.
