### ISSUE TITLE
멘토님 api가 한번만 호출하는 거에 대한 조건에 이해가 안가는게 있습니다.

### ISSUE THREAD

**Issue by yoonucho** [henyy1004/nyangterest#145]
@jongfeel 
멘토님 안녕하세요

멘토링시간에  조건에 따라서 url호출은 한번만 하면 된다고 하셨었는데요

https://github.com/henyy1004/nyangterest/issues/141#issuecomment-600678141

이부분이 조금 이해가 안되어서 질문이 있습니다.
냥터레스트의 기본 리스트를 불러오는 url호출은 한번은 되어야 한다고 생각하는데요 .

 그 상태에서 품종을 선택할시(품종 셀렉트박스)에는  품종 request parameter를 붙여서 다시 호출하는 게 아닐까요

**Comment by jongfeel** [comment]
맞습니다.

제가 한번만 호출하면 된다는 뜻에 대한 설명을 잘 못한 듯 하네요.
요청하는 변수는 바뀔 때 마다 호출하는 건 맞죠
검색어 입력하면 호출하고
날짜 변경하면 호출하는 건 당연한겁니다.
품종이 바뀌면 역시 다시 호출해야 하는 건 맞죠.

다만 parameter를 붙이는게 아니고 바꾸는 겁니다.

전체 품종이 1
선택 품중이 10 이라고 한다면

``` 
// 전체 품종 호출시
http://<endpoint>/.../1/

// 선택 품종 호출시
http://<endpoint>/.../10/
```
이렇게 되면 되겠죠?

변수가 바뀌면 호출되는 건 당연한거고
일단 바뀐 변수에서 호출 한 이후에 추가적으로 다시 호출할 일은 없다는 뜻입니다.
스크롤을 내리면 다음 페이지를 위해 또 똑같은 조건의 변수로 호출하는 일이 없다는 뜻이죠.

**Comment by yoonucho** [comment]
@jongfeel  아! 제가 멘토님의 말씀을 제대로 파악을 못했던거네요  지금은 이해된거 같습니다. 감사합니다.
