### ISSUE TITLE
프론트와 백엔드 그리고 유기동물조회서비스 open api간의 데이터의 흐름을 그림으로 표현해보자.

### ISSUE THREAD

**Issue by yoonucho** [henyy1004/nyangterest#147]

**Comment by yoonucho** [comment]
![Untitled Diagram](https://user-images.githubusercontent.com/2981954/77628989-b98f7c80-6f40-11ea-97d5-6616921d5a42.jpg)

**Comment by jongfeel** [comment]
질문입니다.

파란색으로 표현된 API에서요
1. front -> back으로 요청하는 것과, back -> openAPI 요청하는 파라미터가 같나요?
2. #141 API 합치는 방법에 대해 제안을 드렸는데, request parameter에 보면 페이지 번호가 있네요. 페이지 번호는 다시 추가하기로 한건가요?

**Comment by yoonucho** [comment]
@jongfeel  

* 1번의 답은 기본(검색어가 입력되지 않을때)은 같고 필터링될때는 달라진다고 생각했습니다.

* 아..그런데  2번의 답을 생각하다보니 결국 기본도 구조는 변경을 해야겠다는 생각을 하게되었습니다. 

다시 수정해서 올리겠습니다.

**Comment by jongfeel** [comment]
리뷰해 보다가 또 생각이 났는데요.

한 페이지에 보여줄 결과 갯수 (numOfRows죠?)도 request parameter 라면
UI에 추가하는 방향으로 하면 어떨까요?

![image](https://user-images.githubusercontent.com/17442457/77711377-2758a880-7014-11ea-885d-556e687cce49.png)

그림은 네이버 까페 하코사에서 게시판 기능 중 하나를 가져온 겁니다.
한 페이지에 보여줄 게시물 갯수를 저렇게 정할 수 있다면
의미있는 request parameter가 될 수 있지 않을까요?

**Comment by yoonucho** [comment]
@jongfeel 좋은 아이디어네요!

**Comment by yoonucho** [comment]
![냥터레스트 search data flow-Page-1](https://user-images.githubusercontent.com/2981954/77732854-b0181a00-6ffd-11ea-84dd-57d2d10c0615.jpg)

**Comment by jongfeel** [comment]
또 질문이 있습니다.

1. openAPI -> Back으로 전달되는 데이터하고 하고 Back -> openAPI로 전달되는 데이터하고 같나요?
2. #143 검색 결과 데이터 구조에 대해 제안을 드렸는데, 그림하고 안맞아서요 이렇게 안하고 다른 방법으로 하실 계획이 있는 건가요?

**Comment by yoonucho** [comment]
아...아니네요. back에서 front로 전달하는 데이터와 openApi에서 back으로 전달하는 데이터가 같지 않네요. openApi에서 back으로 전달하는 데이터는 기존하고 동일할테고
back에서 front로 전달하는 데이터는 아이템만 있으면 되겠네요

**Comment by yoonucho** [comment]
![냥터레스트 search data flow-Page-1 (1)](https://user-images.githubusercontent.com/2981954/77760520-6693f300-702e-11ea-999e-fab3f7d6b7cb.jpg)

**Comment by yoonucho** [comment]
문서 업데이트
