### ISSUE TITLE
설계 문서 self check

### ISSUE THREAD

**Issue by jongfeel** [henyy1004/nyangterest#152]
가장 중요한 원칙은
"이 문서를 보고 코딩이 가능한가?"를 스스로 물어보고 체크해 보면 됩니다.

물론 지금은 이미 코딩이 어느 정도 되어 있는 상태이고
거기서 설계 문서를 다시 만든 거라 체크해 보는 건 어렵지는 않을 거에요.

그리고
코딩 하다가 변경된 내용이 있으면 설계 문서에도 업데이트 하는 걸 잊으면 안됩니다.
설계 문서대로 코딩이 될 수도 있고 안될 수도 있는데
설계 문서대로 코딩을 하지 않고 다른 방식이나 설계 문서와는 다른 변경된 내용으로 코딩을 진행했으면, 설계 문서도 업데이트 해주세요.

**Comment by yoonucho** [comment]
네 아직 현재 문서로는 부족함이 있어서 좀 더 보완해야 할듯 합니다
self check 좀더 해보겠습니다!

**Comment by jongfeel** [comment]
업데이트 되면 또 알려주세요.
Pull request로 알려주는게 제일 정확한 방법이겠죠???
