### ISSUE TITLE
작업 하실 때 마음가짐에 대해서

### ISSUE THREAD

**Issue by jongfeel** [henyy1004/nyangterest#154]
스스로 생각하고 만들어 나가는 과정에서
제가 어느 정도 개입하고 있긴 하지만
뭔가 숙제검사 받는 느낌으로 하고 계신거 같아서요.

#153 은 조금 그런 느낌은 덜한데
#149 는 숙제검사 느낌이 너무 강하게 듭니다.

- 코드리뷰를 부탁한다고 얘기 안하셔도 되고
=> reviewer로 저를 넣고 간단한 설명? 정도만 해도 됩니다.
- 뭔가 체크할 내용들에 대해서 자세하게 저한테 보고하는 식으로 안하셔도 됩니다.
=> 코드 라인별로 하나씩 코멘트를 미리 안다셔도 됩니다.
=> 필요하면 제가 질문하는 식으로 하는게 좋은거 같아요.

저랑 내용을 공유하는 차원에서 적어 주시고요.
"내가 이렇게 진행했다 너도 한번 보고 XXX에 대해 의견 있으면 주면 좋겠다."
"나는 이렇게 생각해서 만들었는데, 너의 생각은 어떻냐?"
정도의 코멘트만 해도 충분합니다.

**Comment by yoonucho** [comment]
@jongfeel  아하 네 밸런스 조절하는게 쉽지가 않네요 ㅎㅎ

**Comment by jongfeel** [comment]
조금씩 실천해 보면 될거에요.
