### ISSUE TITLE
25th schedule plan

### ISSUE THREAD

**Issue by jongfeel** [henyy1004/nyangterest#156]
### 1주: 30시간

- 월~금: 오후3시 ~ 오후8시 5시간
- 일: 오후3시 ~ 오후8시 5시간

### 2주: 30시간

- 월~금: 오후3시 ~ 오후8시 5시간
- 일: 오후3시 ~ 오후8시 5시간

나중에 잊어버리지 않기 위해
가능하다면 매일 계획한대로 실천했는지 체크 하시고 기록해 주시면 좋겠습니다.
(알람 계속 와도 상관 없으니까 해주세요)

**Comment by yoonucho** [comment]
200402 Unit test 진행

- [x] 오후 3시부터 8시 까지

유닛테스트 튜토리얼 영상 시청 

* 참고영상
1.  [Unit testing in JavaScript](https://www.youtube.com/watch?v=Eu35xM76kKY&list=PL0zVEGEvSaeF_zoW9o66wa_UCNE3a7BEr)

2.  [OKdevTV 오픈 스터디 ](https://www.youtube.com/watch?v=s2thTTlpiT8)

3.  [OKdevTV 오픈 스터디 - Unit Test, jest #2](https://www.youtube.com/watch?v=APx_sHvyuK8)

* 목표: 유닛테스트 툴 jest의 사용법 익히기

**Comment by yoonucho** [comment]
200403 Unit test 진행

- [x] 오후 3시부터 8시 까지 (5시간은 채웠으나 시간은 계획대로 진행되진 않았다.)

* 3시부터 시작은 하였으나 중간 중간 딴짓을 하게 되어서 새벽까지 합하여 할당량을 채웠다.

* 튜토리얼은 다보고 실제 냥터레스트 server.js 코드를 테스트해보려고 했는데 이거저거 걸리는게 많아서 품종 셀렉트박스를 눌렀을때 나오는 api로 겨우 초록색 PASS를 보게 되었다.

* 데일리리포트할때도 유닛테스트코드를 작성했었는데 그때는 별문제없이 PASS가 되어서 되게 쉬운건줄 알았는데 그렇지는 않구나.

pull request #159 참조

**Comment by yoonucho** [comment]
200407 Unit test 진행
- [ ] 오후 3시부터 8시 까지

**Comment by yoonucho** [comment]
200408 Unit test 진행 예정

- [ ] 오후 3시부터 8시 까지

**Comment by yoonucho** [comment]
200409 Unit test 진행

- [x] 오후 3시부터 8시 까지

**Comment by yoonucho** [comment]
* 시간계획을 세우고 그 시간을 채우려고 보니 그동안 내가 집중을 못했던 시간이  많았구나라는  생각을 하게 되었다.

* 일주일동안 정한 시간대로 진행을 해보았는데  이틀은 펑크를 냈고 매일 5시간은 나에게는 좀 무리였던거 같다.

* 그래서 오늘부터는 오후 3시부터 7시까지 월~금,일  매일 4시간씩으로 변경하려고 한다.

**Comment by jongfeel** [comment]
음 단순히 시간을 채운다는 방식으로 하셔서 힘드셨던 것 같습니다.
- 뭘 할지 정하고 = plan
- 그 다음에 계획한 시간에 실천한다 = action
이 개념으로 생각해 주시면 됩니다.

중간에 변경해서 해도 되는데 처음에 계획했던 것에서 변경하셨으므로
매일 4시간씩 하면 1시간을 달성 못하게 되는 것으로 체크해 주시면 됩니다.

다음 미팅 주기에 맞춰서 일정 체크 및 간단한 회고를 진행하고
그 다음 일정을 어떻게 맞출지 얘기해 보시죠.

**Comment by yoonucho** [comment]
@jongfeel  중간에 변경해서 해도 되는데 처음에 계획했던 것에서 변경하셨으므로
매일 4시간씩 하면 1시간을 달성 못하게 되는 것으로 체크해 주시면 됩니다.

> 음 단순히 시간을 채운다는 방식으로 하셔서 힘드셨던 것 같습니다.
> 
> * 뭘 할지 정하고 = plan
> * 그 다음에 계획한 시간에 실천한다 = action
>   이 개념으로 생각해 주시면 됩니다.
> 
> 중간에 변경해서 해도 되는데 처음에 계획했던 것에서 변경하셨으므로
> 매일 4시간씩 하면 1시간을 달성 못하게 되는 것으로 체크해 주시면 됩니다.

* 이부분이 조금 이해가 안가서요 저는 1주를 진행해보았고 2주째부터는 4시간으로 변경해야겠다고  생각했는데 그러면 저는 2주째는 전부 달성못한게 되는건가요? 

* 음.. 그런거라면 기존대로 5시간으로 하겠습니다. 

> 다음 미팅 주기에 맞춰서 일정 체크 및 간단한 회고를 진행하고
> 그 다음 일정을 어떻게 맞출지 얘기해 보시죠.

**Comment by jongfeel** [comment]
시간을 옮기거나 하는건 되는데요 총 계획된 시간을 바꾸는게 안된다는 뜻이에요.

되는 예)
월요일이 되기 전 월요일 5시간 중 2시간을 하고
나머지 3시간을 화,수,목에 1시간씩 추가해서 진행

안되는 예)
지금 윤우님이 한것 처럼 총 시간을 변경해서 하루 4시간 으로 변경...이 안됩니다. 못한 건 그냥 달성 못하는 시간 체크로 해달라는 얘기입니다.

5시간에서 4시간 했다고 제가 뭐라고 하지 않습니다.  총 계획된 시간에서 1시간씩 달성 못한 걸로 체크하는게 맞다는 거죠.
다음 리뷰 미팅때 점검하고 다시 계획하시면 됩니다.

그리고 이걸 지키기 위해 노력하는건 맞는데
지키지 못한다고 해서 실망하실 필요는 없어요.
그래서 달성률이 70-80%가 될 수도 있고 120-130%가 될 수도 있다고 한겁니다.

**Comment by yoonucho** [comment]
@jongfeel 
아하! 그러면 다음 멘토링시간까지 5시간으로 할게요
네 멘토님이 뭐라고 하시지 않는건 너무 잘 알고 있습니다. 그런데 제가 좀 강박이 있어서  4시간변경은 취소하겠습니다 😸

**Comment by yoonucho** [comment]
200410 Unit test 진행

- [x] 오후 3시부터 8시 까지

**Comment by yoonucho** [comment]
200412 Unit test 진행

- [x] 오후 3시부터 8시 까지

**Comment by yoonucho** [comment]
200413 Unit test 진행
- [x] 오후 3시부터 8시 까지

**Comment by yoonucho** [comment]
200414 Unit test 진행

 - [ ] 오후 3시부터 8시 까지

**Comment by yoonucho** [comment]
200415Unit test 진행

 - [x] 오후 3시부터 8시 까지

**Comment by yoonucho** [comment]
* 4/2 - 4/15  회고

* 총 12일중에 총 10일 *  5시간 = 50시간 
* 4/5, 4/6은 못함 (유닛테스트 튜토리얼이 끝나고 코드를 작성하려니 자꾸 회피하고 싶었다.)
* 이번에 보니 그동안은 생각보다 집중하지 못하고 중간중간 딴짓을 한적이 많았다는걸 깨달았다.
* 그리고 12시에 일어나서 루틴대로 하고 있는것들을 하고나면 3시부터 시작하는게 겨우겨우 맞출 수 있었다. (계속 늦어지긴 했다.)
* 그래서 1시간 더 일찍 일어나서 조금의 여유(?)를 가지게 되었다.
* 처음에는 기존대로 뽀모도로 타이머를 수동으로 멈추고 끄고 하다보니 새벽까지 넘어가서야 할당량을 채우게 되었다.
* 그래서 뽀모도로 타이머를 자동으로 설정했고 (물론 중간 중간 변수로 멈출때도 있었지만) 되도록 그시간은 집중하려고 노력하니 훨씬 수월했다.
* 하지만 매일 5시간은 버겁다. 😭 
* 저녁을 7시에 먹는데 그시간에 밥을먹고 1시간을 다시 해도 되는데 마음이 그게 안되어서 저녁시간이 늦어졌다 ㅋ
