### ISSUE TITLE
200403  Unit test 진행

### ISSUE THREAD

**Issue by yoonucho** [henyy1004/nyangterest#158]
- [ ] 오후 3시부터 8시 까지

**Comment by yoonucho** [comment]
* 오늘은 3시부터 시작은 하였으나 중간 중간 딴짓을 하게 되어서 새벽까지 합하여 할당량을 채웠다.
![주석 2020-04-04 001821](https://user-images.githubusercontent.com/2981954/78376942-8727f400-75be-11ea-9136-11e36feff7f2.jpg)

**Comment by yoonucho** [comment]
* 튜토리얼은 다보고 실제 냥터레스트 server.js 코드를 테스트해보려고 했는데 이거저거 걸리는게 많아서  품종 셀렉트박스를 눌렀을때 나오는 api로 겨우 초록색 PASS를 보게 되었다.

* 데일리리포트할때도 유닛테스트코드를 작성했었는데 그때는 별문제없이 PASS가 되어서 되게 쉬운건줄 알았는데 그렇지는 않구나.
 
![주석 2020-04-04 001835](https://user-images.githubusercontent.com/2981954/78376927-842d0380-75be-11ea-9021-1c26192bad56.jpg)

**Comment by jongfeel** [comment]
품종 셀렉트박스를 눌렀을때 나오는 api

이 코드를 볼 수 있을까요?

**Comment by jongfeel** [comment]
pull request #159 참조
