### ISSUE TITLE
작업 하실 때 마음가짐에 대해서 part 2

### ISSUE THREAD

**Issue by jongfeel** [henyy1004/nyangterest#160]
part 1은 #154 참고하시면 되고요
이 issue는 #159 에서 부터 왔습니다.

잘 안된다고 하는 걸 숨기지 마시고
안되는게 뭔지, 어떤 문제가 있는지 공유를 하고 함께 알아나가는 과정이 더 중요하다고 봅니다.

앞으로 숨기지 말고 (부끄러워하지 말고) 공유해 주세요.

**Comment by yoonucho** [comment]
@jongfeel  네 좀 부끄럽지만 공유하겠습니다.

**Comment by jongfeel** [comment]
그러면 #159 에도 comment 했지만
안되는 부분에 대한 내용을 pull request 주세요.

**Comment by yoonucho** [comment]
@jongfeel  네 좀더 해보고 안되면 pr드릴게요
