### ISSUE TITLE
server.js를 require하면 아래와 같은 에러가 나온다.

### ISSUE THREAD

**Issue by yoonucho** [henyy1004/nyangterest#162]
![주석 2020-04-08 152700](https://user-images.githubusercontent.com/2981954/78751714-43d4d900-7962-11ea-8f43-afcdf6c60153.jpg)

해당 코드는  login 파일에 대한 코드인데 login에 대한 코드를 주석처리해도 변함이 없다.

결국 login관련 require된  모든 파일을 주석처리해야 관련 메세지가 사라지는데 이거에 대한 근본적인 해결방법이 필요하다.

에러코드에 나온 jest 공식문서에 들어가서 https://jestjs.io/docs/en/configuration#teste에 들어가서 하라는대로  package.json에   넣으라는 코드를 넣어서 소용이 없다.
<pre>
"jest": {
    "verbose": true
  }
</pre>

**Comment by yoonucho** [comment]
@jongfeel 로그인과 연관된 파일에 대한 코드를 전부 주석처리해야 에러메시지가 나오지 않는 상황인데요 이부분을 지금처럼 주석처리하고 테스트해도 될까요? 아니면 이부분을 주석없이 해결하고 진행하는게 맞을까요

**Comment by jongfeel** [comment]
에러가 뭔지 확인하고 해결하는 과정이 필요하지 않을까요?
자꾸 피하려고만 하지 마시고 분석하고 해결해 나가려고 해주세요.

일단
에러 메시지를 보면 왜 에러를 내는지 알려주고 있습니다.
session 생성 과정에서 setInterval에 문제가 있는 것 같습니다.
해당 에러 메시지로 구글 검색을 해보면 해결 방법을 알려주고 있고요

https://github.com/facebook/jest/issues/9033
https://github.com/googleapis/nodejs-firestore/issues/783

**Comment by yoonucho** [comment]
@jongfeel  네 그러면 에러먼저 해결하고 테스트를 진행하도록 하겠습니다.

**Comment by jongfeel** [comment]
session 관련된 문제라면 로그인 테스트를 진행하고 그 후에 api 테스트를 해야할 수도 있습니다. 그 점도 고려해 보세요.

**Comment by yoonucho** [comment]
@jongfeel  그런데 어제까지는 주석을 안하면 에러가 났었는데 오늘 다시 테스트 실행하니 어쩐일인지 그부분은 그냥 해결이 되었습니다.
