### ISSUE TITLE
**Unit Test 심화**

### ISSUE THREAD

**Issue by yoonucho** [henyy1004/nyangterest#168]
### 4/16 ~ 4/20 (일시중단) (16,17,18,20)
**무엇을 더 테스트할 것인가**

* - [x] 예외처리는  왜 필요한가 

* - [x] 예외처리 할 부분을 찾기

* - [x] 예외처리는 어떻게 해야 하지?
  
* - [x] 항상 변하지 않는 값 찾기 

* - [x] 항상 PASS할 수 있는 시나리오 생각하기

* - [ ] 기존 코드 수정 및 추가하기

**Comment by jongfeel** [comment]
체크하신 부분들에 대한 내용 정리가 된 부분이 있으면 문서 링크 남겨주세요.

**Comment by yoonucho** [comment]
#170 에 등록해두었습니다
