### ISSUE TITLE
멘토님  작업을 진행하는 중에 고민되는 부분이 생겨서 이슈로 올립니다.

### ISSUE THREAD

**Issue by yoonucho** [henyy1004/nyangterest#171]
#170 에서  변하지 않는 값중 한 페이지 결과 수(72)를 넣어서 테스트 해보는데  fail이 나왔고
아래와 같이 결과가 나왔습니다.

![주석 2020-04-18 174210](https://user-images.githubusercontent.com/2981954/79633196-f6950a80-819e-11ea-994b-fe69c44369e2.jpg)

server.js 코드를 보니 제가

```javascript
const baseUrl = `${api}/abandonmentPublic?ServiceKey=${serviceKey}&_type=json&bgnde=${bgnde}&endde=${endde}&numOfRows=1000&upkind=422400&`;
```
numOfRow값을 하드코딩으로 1000(결과보다 큰 수 )이라 넣어두었는데  아직 [검색기능 설계서](https://github.com/henyy1004/nyangterest/wiki/%EC%9C%A0%EA%B8%B0%EB%8F%99%EB%AC%BC-%EC%A0%95%EB%B3%B4-%EC%A1%B0%ED%9A%8C-%EC%84%9C%EB%B9%84%EC%8A%A4%EC%9D%98-%EA%B2%80%EC%83%89-%EA%B8%B0%EB%8A%A5-%EC%84%A4%EA%B3%84%EC%84%9C#5-data-flow) 대로 실제코드를 수정하지 않아서  문제가 발생하였습니다.

이럴때는 그대로 1000이라는 값으로 테스트를 해야할까요 아니면 유닛테스트전에 설계서대로 수정하는게 먼저일까요 또는  server.js에 하드코딩한 1000이라는 값을 72로 바꾸고 테스트를 진행해야할까요

**Comment by jongfeel** [comment]
음 이런 경우라면 설계서대로 수정 후 테스트를 진행하는게 먼저인 듯 싶습니다.

**Comment by yoonucho** [comment]
@jongfeel  우선 질문드린거 이외의 부분을 테스트 중이었는데 그러면 코드를 수정하는 작업으로 계획을 다시 변경하겠습니다. 그런데 설계서가 있는상태면 바로 코드를 수정해도 될런지요 아니면 제가 무엇을 준비해둬야 할런지요

**Comment by jongfeel** [comment]
설계서 대로 수정 진행하시고
수정하다가 설계서 대로 진행이 안되거나 바꿔야 겠다고 생각이 드시면
어느 부분의 설계를 수정했는지를 잘 적고 (히스토리 관리) 진행하시면 됩니다.

원래 설계서가 있는 상태에서 바로 코딩하는게 **정상**입니다.
