### ISSUE TITLE
* #172 데이터 구조를 바꾸고나서 보니 해결했었던  이슈들이 다시 발생했다.

### ISSUE THREAD

**Issue by yoonucho** [henyy1004/nyangterest#175]
* 기존에 아이템 조건을 배열이냐 아니냐로 구분했었는데

* 바뀐 기본 아이템의 타입이 배열이니깐 아이템이 하나일때나 아이템이 없을때 조건을 어떻게 해야할지 좀더 고민해봐야할거 같다.

* 해당품종이 없을때 이슈
![주석 2020-04-26 210519](https://user-images.githubusercontent.com/2981954/80307454-1615de00-8804-11ea-8202-2ebc24b44482.jpg)

* 아이템이 하나만 있을때 이슈인데 윈도우객체를 돌고 있는거 같다.

![주석 2020-04-26 210802](https://user-images.githubusercontent.com/2981954/80307462-29c14480-8804-11ea-9cbe-49c7b4bf97f5.jpg)

**Comment by yoonucho** [comment]
* 아이템이 하나만 있을때는 이슈는 해결 
  * 아이템이 하나일때 constructor.name이 Object다. Object를 Array로 만들어줘서 해결 

// server.js
```javascript
      // 1보다 클때
	if (totalCount > 1) totalItems = defaultItem || []

	// 1보다 작거나 같을때 (totalItems.constructor.name === Object)
	else if (totalCount <= 1) totalItems = [defaultItem]

```

//listStore.js
```javascript
   runInAction(() => {

      
      if (Array.isArray(json.items[0])) {
        this.setItems([...items, ...(json.items[index] || [])]);
       }
     // 중략 
```
*

**Comment by jongfeel** [comment]
이런 예외도 test case가 있으면 좋습니다.

**Comment by yoonucho** [comment]
@jongfeel  넵 나머지 이슈를 해결하고 유닛테스트 작성할때 추가하겠습니다!

**Comment by yoonucho** [comment]
아이고 두번째 이슈를 결국 해결 하지 못하였다 ㅠㅠ

**Comment by yoonucho** [comment]
![주석 2020-04-26 210519](https://user-images.githubusercontent.com/2981954/80307454-1615de00-8804-11ea-8202-2ebc24b44482.jpg)

* 해당날짜에 선택한  품종이 없을시 발생하는 이슈는 defaultItem(defaultRes.items.item)의 타입이 undefined이라 생기는 이슈인듯 싶다.

* 그러면 defaultItem을 배열로 만들면 해결이 되겠다 싶어서 아래와 같이 추가하였다.

//server.js
```javascript

   if (typeof defaultItem === 'undefined') defaultItem = []
```

* 그런데 결과는 배열의 늪에 빠지게 되었다. 총체적 난국.. 😭 

![주석 2020-04-28 165932](https://user-images.githubusercontent.com/2981954/80484100-1e038880-8992-11ea-8a74-efdffe11b265.jpg)

*  4시간 내내  시도하였으나 결국 이슈를 잡지 못하였다.

**Comment by jongfeel** [comment]
> 이런 예외도 test case가 있으면 좋습니다.

test case가 undefined, null이어도 의도된 테스트라면 pass를 해줄 수 도 있습니다.
