### ISSUE TITLE
멘토님 response parameter로 totalCount가 프론트엔드에서 필요할거 같습니다.

### ISSUE THREAD

**Issue by yoonucho** [henyy1004/nyangterest#193]
멘토님 https://github.com/henyy1004/nyangterest/pull/180#discussion_r422726023 관련하여 재질문을 드립니다. 
server.js에서는 totalCount를 멘토님이 말씀하신대로 for문으로 돌려서 구해도 되긴하는데 문제는 
totalCount가  프론트엔드에서도 필요할듯합니다.

그 이유는 아래와 같이 totalCount와 (numOfRows * (index + 1))의 값을 비교하는  totalPage함수로 페이징여부를 처리하는데요.  totalCount가 없다면 여기서도 for문으로 돌려야 전체 갯수를 구할 수 있을거 같은데 그렇다면 같은 로직이 중복되느니 totalCount를 받아오는게 더 낫지 않을까요?

//listStore.js

```javascript
@computed
	get totalPage() {
		const { index, numOfRows, totalCount } = this;
		let paging = Math.ceil(numOfRows * (index + 1)) >= totalCount
		return paging;
	}

``

```javascript
@action
	loadMore = () => {

		const { totalPage } = this;

		let message = observable({
			return: "마지막 페이지입니다.",
			continue: "데이터가 남아있습니다."
		})

		if (totalPage) {
			return console.log(message.return)
		}
		else {
			console.log(message.continue)
			this.isLoading = true;
			this.scrolling = true;
			this.index++;
			this.loadList();
		}
	}
```

**Comment by jongfeel** [comment]
count 구하는 로직은 front에만 있는거에요.
서버에서는 count를 구하지 않아요.

그래서
https://github.com/henyy1004/nyangterest/pull/180#discussion_r422874509
이슈에 totalCount는 구하지 않아도 된다고 얘기한거였습니다.
이렇게 하면 front에는 items만 넘기는 거라고 했죠.

**Comment by yoonucho** [comment]
그러면 https://github.com/henyy1004/nyangterest/pull/180#discussion_r422874509 에서 멘토님이 totalCount를 for문으로 돌리는 로직은 server.js가 아니라 프론트엔드에서 필요하다고 말씀하신것인지요

**Comment by jongfeel** [comment]
네 맞아요

**Comment by yoonucho** [comment]
아하! 저는 server.js에 필요한 로직이라고 생각을 했습니다.
왜냐면 server.js에서 totalCount의 값으로  언디파인드나 아이템갯수가 하나일때 조건인 코드를 만들었었기 때문입니다.

**Comment by jongfeel** [comment]
아 다시 보니 제가 설명을 빠뜨렸군요.

totalCount를 front로 안보내면 된다는게
server에서 구하지 말라는 얘기가 포함이 된건데
실제로는 적지는 않았네요.

**Comment by yoonucho** [comment]
다시 정신을 차리고 생각해보니 프론트엔드에서 언디파인드나 아이템하나일때를 처리할 수 있다면  totalCount자체가 server.js에서는 아예 필요없는게 맞겠구나 라는 생각이 드네요! 
감사합니다!

**Comment by jongfeel** [comment]
그런데 그렇게 되면 또 server에서 처리해야 할 걸
front에서 처리해야 할 것들로 바뀌니까 크게 의미가 없어집니다.

그런 예외처리는 server에서 그대로 처리하고
항상 같은 데이터 포맷인 [[]] 형태로 줄 수 있게만 하면 되요.

front는 항상 [[]] 형태로 데이터를 받는다는 걸 확신할 수 있으면 front쪽 코드는 수정 안해도 되니까요.

**Comment by yoonucho** [comment]
네 그러면 server.js에서 예외처리를 어떻게 해야할지 생각해 봐야겠네요

**Comment by yoonucho** [comment]
궁금증이 해소되어서 닫습니다.
