### ISSUE TITLE
ML 관련 개념 잡기

### ISSUE THREAD

**Issue by jongfeel** [henyy1004/nyangterest#21]
예전에 ML(Machine Learning)을 클라우드 서비스 사용하면 쉽다고 얘기했었는데
AWS는 회원 가입 해야 쓸 수 있는 반면에 Azure는 무료 튜토리얼이 있습니다.
아래 Azure 링크를 열어 보신 후에
고양이 사진이 있는 URL을 입력해 보면 기가 막히게 고양이인지 아닌지 인식합니다.

https://azure.microsoft.com/ko-kr/services/cognitive-services/computer-vision/

제가 아무 고양이 사진 URL을 넣었을 때 인식 결과
고양이: 0.999
실내: 0.999
앉아있음: 0.972
흰색: 0.952
동물: 0.936
...

![image](https://user-images.githubusercontent.com/17442457/59822846-fd78a400-9366-11e9-8381-51f542738bba.png)

이걸로 서비스를 어떻게 만들어 볼지에 대한 힌트를 얻어 보시고 적용 계획을 세워 보시면 좋을 거 같습니다.

**Comment by yoonucho** [comment]
헉 5일전에 쓰신글을 이제 봤네요! 감사합니다 참고하겠습니다!

**Comment by jongfeel** [comment]
괜찮습니다.

다음 부터는
@yoonucho @henyy1004 
요렇게 해서
메일이 바로 가게 해드릴께요.
(물론 메일을 확인 하냐 안하냐의 문제는 논외겠죠?)
