### ISSUE TITLE
검색 박스 반응형작업시 이슈 해결방법 모색

### ISSUE THREAD

**Issue by yoonucho** [henyy1004/nyangterest#214]

**Comment by yoonucho** [comment]
@henyy1004 

혜인님  제가 해결하고 싶은 부분은  해상도 width 960미만일때 검색박스가  활성화가 되었을때만 ul 상단에 패딩을 주어서 가려지는 부분을 보이게 하고 싶습니다!

제가 지금 반응형작업을 다시 수정하고 있는데요
기존에는 해상도 width 1024미만일때 검색박스는 스크롤을 내렸을때 고양이리스트와 같이 넘어가게 했었는데 UX적으로 불편하다는 생각이 들어서 아래와 같이 해상도 width 960미만일때 스크롤을 내려도 검색박스는 고정하게끔 변경하였는데요 

문제는 해상도가 좁아짐에 따라 3개의 검색창이  아래로 떨어지는 형태고 이게 제일 상단 고양이 리스트를 가리게 되는 문제가 발생하였습니다.

검색버튼을 클릭했을때 리스트 상단에 패딩을 주어서 상단 고양이 리스트도 가리지 않게끔 하고 싶은데요 구조상 바꾸기에 어려움이 있습니다. 

대략적인 구조는 아래와 같습니다.

```jsx
<div>
    // 검색박스 활성화
    <SearchDiv>
        <Form className="slide-in">
           // 중략
        </Form>
        // 검색 버튼 
        <TooltipBox>
            // 중략
        </TooltipBox>
     </SearchDiv>
  // 고양이 리스트
    <List>
       // 중략
    </List>
</div>

```

![ezgif com-video-to-gif (6)](https://user-images.githubusercontent.com/2981954/84630509-0030b980-af27-11ea-8293-0d49ea8176a5.gif)

![주석 2020-06-15 163840](https://user-images.githubusercontent.com/2981954/84630546-0f176c00-af27-11ea-998a-346f1aa2ca19.jpg)

![주석 2020-06-15 163808](https://user-images.githubusercontent.com/2981954/84630562-176fa700-af27-11ea-983f-829c9e497886.jpg)

**Comment by henyy1004** [comment]
@yoonucho 
윤우님 필터 열리고 닫힐때 `SearchDiv`에 클래스추가 했구요
그 클래스로 바로 옆에있는 `item-list`의 여백을 조절했어요
여백들이 vh와 %단위로 되어있어서 레이아웃이 뷰포트영향을 많이 받더라구요
이 영역에 vh,% 단위는 크게 중요하지 않을 것 같아 고정px로 넣었습니다~

**Comment by yoonucho** [comment]
@henyy1004  감사합니다!
