### ISSUE TITLE
UI 반응형 무한 스크롤 이슈- 모바일 화면에서 유기묘 리스트 스크롤 기능 분석

### ISSUE THREAD

**Issue by yoonucho** [henyy1004/nyangterest#216]
6/20 ~ 6/22

width 700이하에서도 일정간격으로 무한 스크롤링이 되었으면 좋겠다.

**Comment by jongfeel** [comment]
궁금해서 그러는데요

- 어떤 문제가 있는 건지? (아예 안되는 건지? 동작이 이상한건지? )
- 왜 스크롤링이 더 필요하다고 생각하는지?
- 일정 간격이라는게 어떤 의미인지?

를 알 수 있을까요?

**Comment by yoonucho** [comment]
@jongfeel  

this.loadMore()함수가 모바일일때 는 100개의 아이템이 보여지고는 스크롤링이 안되는 이슈가 있습니다.
그래서  별도로 아래의 코드를 넣어서 해상도 width 700이하일때는 무조건 스크롤링이 되게끔 해놓았는데  성능적으로나 기능적으로는 적절하지 않다는 생각이 듭니다.

https://github.com/henyy1004/nyangterest/blob/cb376ff5714d1bbe808b936549da00591095e2c1/packages/frontend/src/Stores/listStore.js#L99


제생각에는 스크롤링이 되는 조건은 totalPage가 참이어야 하는데 

https://github.com/henyy1004/nyangterest/blob/cb376ff5714d1bbe808b936549da00591095e2c1/packages/frontend/src/Stores/listStore.js#L125

이 조건이 폰에서는 참이 안되어서 스크롤링이 안되는거 같습니다.

**Comment by jongfeel** [comment]
설계 부분은 오히려 단순할거 같으니
코드 분석 계획을 세우고 진행해 보면 어떨까요?

"width 700 이하 문제점 해결"이라는 개발자 스러운 요구사항 말고
"모바일 화면에서 유기묘 리스트 스크롤 기능 분석" 이라는 기획에 가까운 요구사항을 만들고 시작해 보면 좋겠습니다.

**Comment by jongfeel** [comment]
노파심에서 말씀드리면 "코드 분석"이지 "잘 모르겠고 일단 코딩부터 시작"이 아님을 주의해 주세요.

**Comment by yoonucho** [comment]
@jongfeel  네 명심하겠습니다!

**Comment by yoonucho** [comment]
### 무한 스크롤이 되는 조건

* scrolledToBottom이 true가 되어야  this.loadMore()함수가 실행된다.

* 웹상에서는 scrolledToBottom이 true가 되는 조건이 성립되어 다음 페이지(사실은 인덱스)로 넘어간다.

* 모바일일때는 scrolledToBottom이 false라 스크롤링이 되지 않는다.

### 모바일에서 false가 되는 이유?

* 유기묘 리스트의 아이템이 한 화면에 하나씩밖에 보이지 않아서 그런거 같다는 생각이 든다.

(분석전에는.loadMore()함수가 설립하는 조건인 totalPage 조건이 모바일에서는 성립이 되지 않아서라고 생각을 했었지만 이건 좀 더 뒤에 생각해보자)

### 그럼 태블릿에서는 ?

**Comment by yoonucho** [comment]
모바일 화면에서 유기묘 리스트 스크롤 기능 분석 문서(https://github.com/henyy1004/nyangterest/wiki/%EB%AA%A8%EB%B0%94%EC%9D%BC-%ED%99%94%EB%A9%B4%EC%97%90%EC%84%9C-%EC%9C%A0%EA%B8%B0%EB%AC%98-%EB%A6%AC%EC%8A%A4%ED%8A%B8-%EC%8A%A4%ED%81%AC%EB%A1%A4-%EA%B8%B0%EB%8A%A5-%EB%B6%84%EC%84%9D)
