### ISSUE TITLE
Preview server.js pull request

### ISSUE THREAD

**Issue by jongfeel** [henyy1004/nyangterest#218]
@yoonucho 님은 필수
@henyy1004 님은 선택

### Overview

예전에 server.js refactoring과 unit test를 진행했을 때, 제가 완료를 하고 난 이후에 제가 생각하는 refactoring에 대한 pull request를 드린다고 했었고, 이제 해봐도 될 것 같은 생각이 듭니다.

### Request for pull request

- server.js를 실행할 떄 공공 API 호출 시 필요한 process.env.SERVICE_KEY 값이 필요합니다. (따로 전달해 주세요)
- 아주 조금씩 commit을 하고 pull request를 드릴 예정입니다.

### Purpose

- Unused clean up code
- Review refactoring
- Code reviewer experience

**Comment by yoonucho** [comment]
@jongfeel 네 메일로 보내드리겠습니다! 감사합니다!
