### ISSUE TITLE
#222 프로젝트 버그 원인 분석

### ISSUE THREAD

**Issue by yoonucho** [henyy1004/nyangterest#223]
6/24 

- [x] 버그 재현 시도하기

https://github.com/henyy1004/nyangterest/issues/222#issuecomment-648659626

**Comment by jongfeel** [comment]
#222 의 경우는 제 환경이므로 재현하기 어려울 수 있습니다.

조금의 단서를 찾거나 뭔가 해보고 판단해야 할 경우 언제든지 코멘트 달아 주세요.

이 문제의 경우는 혼자 시간쓰는 것 보다 저와의 커뮤니케이션을 통한 피드백이 매우 중요합니다.

**Comment by yoonucho** [comment]
@jongfeel 
네 알겠습니다!
