### ISSUE TITLE
실제 프로젝트에 mobx 적용해보기(현재는 실패 ㅠㅠㅠ)

### ISSUE THREAD

**Issue by yoonucho** [henyy1004/nyangterest#23]
* 며칠전에 시도해봤으나 
상태관리를 해야 할 부분과 안해야 할 부분의 분리가 잘 안되어서 그런가 실제 적용해보기가 너무 어려움 ㅠㅠ 
좌절좌절 멘탈나감 
* 그래도 다시 도전을..
* 아아아아 모르겠다. 우선 Hook으로 리팩토링후 다시 시도봐야지.

**Comment by jongfeel** [comment]
@yoonucho 

제가 좀 찾아보니까 typescript 기반으로
annotation 설정 해 주면 좀 쉽게 redux를 대체할 수 있는 기능으로 보이는데
미팅 때 잠깐 리뷰해 보는것도 좋을 거 같네요

**Comment by yoonucho** [comment]
@jongfeel 
네 저도 우선 하는데까지 해보겠습니다 ㅠ
