### ISSUE TITLE
회원가입 form 입력정보 backend넘기기

### ISSUE THREAD

**Issue by henyy1004** [henyy1004/nyangterest#25]
회원가입기능을 구현하기 위해서
data를 디비에 저장하는 작업을 진행하였고 일단 세가지 단계로 분류하여 작업중이었습니닷

1. 입력된 `state data`를 `json`으로 변환
2. 변환된 `json data`를 `fetch`를 사용하여 `backend`로 넘기기
3. 넘겨진 data 쿼리문 사용하여 db에 저장

2단계작업에서 막히기 시작했는데요ㅠㅠㅠ
프론트단에서 받아져온 json데이터가 console.log로 확인했을때
빈객체로 받아져와서 어려움을 격고있습니다................엉엉

**Comment by jongfeel** [comment]
front에서 request 할 때 header의 content-type을 넣어주면 되네요.

``` javascript
fetch('/', {
			headers: {
				'Accept': 'application/json',
				'Content-Type': 'application/json'
			},
			method: 'POST',
			body: stateTojson
		});
	}
```
