### ISSUE TITLE
멘토링 후 mobx 다시 적용하기 (조금씩)

### ISSUE THREAD

**Issue by yoonucho** [henyy1004/nyangterest#26]
1. List.js에서 상태로직을 분리하여 Store환경 구성 
2. mobx문법에 맞게 코드 변경 작업
3. 프로젝트 서버 실행했을시에 리스트 화면 나오는것은 성공했으나 이후 스크롤을 내렸을때 무한로딩후 반응이 없음 콘솔로 찍어보니 페이지수가 늘어나지 않음

변경한 부분 코드비교 링크: (https://github.com/henyy1004/nyangterest/pull/27)

**Comment by jongfeel** [comment]
Mobx 적용
- 기술의 접근 자체가 다르므로, 그 생각과 철학을 이해하려는 노력이 중요
- 주요 키워드로는 mvvm, two way binding
- 한쪽 기술에 너무 치우쳐저 있으면 장단점이 존재하는데
  - 장점: 일을 시키는 사람 입장에서 일 설명하고 할당하기 좋음, 연차가 적을 때 경력 관리하기 좋음
  - 단점: 장기적으로 한가지만 한 사람은 다른 일과 다른 환경의 개발을 잘 하지 못하므로 분석, 설계를 해야할 타이밍에 제대로 못하고 옛날 개발자 될 가능성 높음
- 경험삼아 적용해 봐도 좋고, 나중에 mobx 관련해서 설명할 때 어떤 특징을 가진 것인지를 설명하고 어필할 수 있도록 하는 것이 좋음

**Comment by yoonucho** [comment]
드디어 가닥을 잡은거 같습니다. 페이지수를 넘기지 못해서 계속 로딩중만 떠있었는데 제대로 페이지를 받아오네요 ㅎㅎ;
