### ISSUE TITLE
혜인님 master에 푸시한거 제가 날려먹었어요!

### ISSUE THREAD

**Issue by yoonucho** [henyy1004/nyangterest#32]
@henyy1004 혜인님 멘토님 미팅기록 풀리퀘 수락할때 제가 커밋명을 잘못써서 그거 바꾼다고 리베이스작업좀 했는데 그이후에 커밋된 혜인님 커밋이 날라간거 같아요 
죄송하지만 혜인님이 다시 푸시해주세요 ㅠㅠ

**Comment by henyy1004** [comment]
@yoonucho  확인 늦어서 죄송해요! 제 로컬 마스터브랜치로 덮어씌웠습니당~
