### ISSUE TITLE
혜인님 ~ 필터 이용툴팁 의논 후 추가적으로 질문이 있어서요. 

### ISSUE THREAD

**Issue by yoonucho** [henyy1004/nyangterest#39]
1.구현방법: 사이트에 접속하자마자 필터 툴팁의 내용이 오픈되고 오늘 하루 보이지 않기 버튼으로  창을 닫음

2. 오늘 하루 보이지 않기는 쿠키나 세션처리를 해야함

[질문]
1. 저는 이렇게 생각하고는 있었는데  혹시 툴팁박스도 로그인해야 보이는 방식인지요

2. 오늘 하루 보이지 않기는 저는 React-cookie로  구현을 생각했었는데 
아무래도 혜인님이  로그인 구현을 어떻게 하실지를 알아야 할거같아서요
혜인님이 구현하시면 제가 혜인님 코드를 토대로  작업진행하는게 어떨까요?

시간되실때 보시고 답변주셔요~

**Comment by henyy1004** [comment]
1. 윤우님이 생각하신 방식이 맞습니다~

2. 넵 그렇게 해요! 로그인 방법을어떻게 구현할지 먼저 생각해보겠습니다~

**Comment by yoonucho** [comment]
넵넵!
