### ISSUE TITLE
인증링크로 접속시 쿼리데이터 전달이 안되는것 같아요

### ISSUE THREAD

**Issue by henyy1004** [henyy1004/nyangterest#40]
@yoonucho 

인증링크를 메일로 보낸 후 링크로 접속을하면
`server.js` 에서 query문의 `email`과  `token` 값을 받아
 console.log로 확인하려고했습니다
하지만 현재 상태는 링크로 접속하면 쿼리문을 못받아오는 것 같아요ㅠ_ㅠ
(왜냐면 console.log가 찍히지 않음)

다만 postman으로 쿼리문을 보내면 console.log가 찍힙니다.
다만 찍힌 후 
~~~
Proxy error: Could not proxy request /welcome?email=qwer from localhost:3000 to http://localhost:8080.
[1] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).
~~~
프록시 관련 에러가 납니당ㅠㅠㅠㅠ 
헬프드려요..!

**Comment by yoonucho** [comment]
@henyy1004  넵 브런치받아서 살펴보도록 하겠습니다!

**Comment by henyy1004** [comment]
@yoonucho ~~~js
const emailLink = `http://localhost:3000/welcome?email=${email}&token=${emailToken}`;
~~~
를
~~~js
const emailLink = `http://localhost:8080/welcome?email=${email}&token=${emailToken}`;
~~~
로 변경하여서 해결!
도움주신 윤우님 감쟈합니다~~~
