### ISSUE TITLE
멘토님 며칠내내 이거저거 시도해보았으나 원하는 결과를 얻지 못하여 이슈에 등록해둡니다. ㅠㅠ

### ISSUE THREAD

**Issue by yoonucho** [henyy1004/nyangterest#5]
@jongfeel  @henyy1004  멘토님 안녕하세요! 

프로젝트 진행중에 저와 혜인님이 머리싸매고 며칠을 고민하고 시도하였으나 저희가 원하는 결과(유기묘사진이미지와 타이틀 데이터를 받아서 화면에 출력)가 나오지 않아서 문의드립니다.

우선 data.go.kr의 표준포맷이 xml이지만 json으로 다운이 되니 이걸 제 서버에 올려두고 테스트 해보면 되겠지라는 안일한 생각을 가지고 진행을 하였었습니다. [json파일경로 ](https://s3.ap-northeast-2.amazonaws.com/web1-html-internet-yu/cats-info04.json)
그런데 cors 정책에 [Cross-origin resource sharing의 약자입니다. 위키백과를 링크걸어둡니다.](https://ko.wikipedia.org/wiki/%EA%B5%90%EC%B0%A8_%EC%B6%9C%EC%B2%98_%EB%A6%AC%EC%86%8C%EC%8A%A4_%EA%B3%B5%EC%9C%A0) [영문도 링크걸어둡니다.](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing)
막혀서 에러가 뜨더라고요 
이걸 해결할수 있는 방법에 대해서 모색해보았고 이거저거 시도해보았습니다.

* [구글확장프로그램](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi) 설치
* 리액트 packages.json에서 프록시설정 등등 해보다가 도저히 안되어서 
우선 로컬파일을 연결해서 해보자 싶어서 경로를 설정해주고 시도해보았으나 불러오지를 못하였습니다. 그래서 아예 App.js에  state에 직접 파일내용을 복사해서 붙여넣기를 하고 시도해보니 원하는 결과가 나오긴 하였습니다. [해당 브렌치이름은 feature/yu-main_test이며 App.js내용입니다.](https://github.com/henyy1004/nyangterest/blob/feature/yu-main_test/packages/frontend/src/Components/App.js)

그러고 다시  로컬파일을 연결을 재시도해보았고 실제데이터를 파싱도 시도해보았습니다.
실제데이터인  xml 파싱은 node모듈인 fs로  연결하여 node 명령어를 실행했을때 json으로 변환하여 node명령어로 실행했을때는 json으로 변환해서 보여졌으나  [해당브렌치 이름은 feature/xml_test이며 xmlParser.js내용입니다. ](https://github.com/henyy1004/nyangterest/blob/feature/xml_test/packages/backend/xmlParse.js)

리액트에서 적용해보려고 하였으나  원하는대로 결과를 얻지 못하였습니다.

또 cors적용을 하려면 backend가 있어야겠다는 생각이 들어서 backend폴더를 만들어서 koa와 cors설정을 하였고 frontend를 연결하려고보니 막막해졌습니다. 
dbms없이 frontend를 연결할 수 있는것인지 맞는건지도 모르겠고 그런데 지금은  db가 필요없는 상태 아닌가  이런 저런 생각과 고민이 듭니다.

**Comment by jongfeel** [comment]
@yoonucho @henyy1004 

왠지 크로스 도메인 문제인 듯 하군요.

https://nesoy.github.io/articles/2017-06/Cross-Domain
요 부분을 보고 한번 분석을 해 보시고

크로스 도메인 이슈는 비교적 쉽게 해결이 가능하므로 적용해 보시면 될 거 같고요.

step by step으로 문제를 잘 쪼개고 분석해서 해결해 나가 보면 좋을 것 같습니다.

- localhost, frontend에서 => data.go.kr 호출
- localhost, backend에서 => data.go.kr 호출
- www.nyangterest.com frontend에서 => data.go.kr 호출
- www.nyangterest.com backend에서 => data.go.kr 호출

뭐가 되고 안되는지, 그리고 안되는 이유가 뭔지 정리가 되면 공부가 될 겁니다.

**Comment by yoonucho** [comment]
넵 아무래도 기록을 해야 할거 같습니다 ㅎㅎ
